food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('product_list/', views.product_list, name='product_list'),
    path('cart/', views.cart_view, name='cart_view'), 
    path('cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/delete/<int:item_id>/', views.delete_order_item, name='delete_order_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('deliver/', views.deliver, name='deliver'),
    path('preparing/', views.preparing, name='preparing'),
    path('served/', views.served, name='served'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('food.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/',  null=True, blank=True)
    def __str__(self):
        return self.name

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    checkout = models.BooleanField(default=False)
    def __str__(self):
        return f"Order {self.id} by {self.user.username}"

    def get_total(self):
        return sum(item.get_total() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    def get_total(self):
        return self.quantity * self.product.price

food/forms.py
# myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text="Required. Inform a valid email address.")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

food/views.py
from .models import Product, Order, OrderItem
from .forms import SignUpForm
from .signals import order_completed
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group

def is_staff(user):
    return user.groups.filter(name='Staff').exists()

def is_customer(user):
    return user.groups.filter(name='Customers').exists()
# Create your views here.

def logout_view(request):
    logout(request)
    # Redirect to a success page.
    return redirect('food:login')

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            customers_group = Group.objects.get(name='Customers')
            # Add the user to the group
            user.groups.add(customers_group)
            login(request, user)  # Log the user in after successful sign-up
            return redirect('food:product_list')  # Redirect to home or any other page
    else:
        form = SignUpForm()
    return render(request, 'food/signup.html', {'form': form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"You are now logged in as {username}.")
                print('1')
                if user.groups.filter(name='Customers').exists():
                    print('2')
                    return redirect('food:product_list')
                elif user.groups.filter(name='Staff').exists():
                    return redirect('food:deliver')  # Replace with your desired redirect
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = AuthenticationForm()
    return render(request, "food/login.html", {"form": form})

@login_required
@user_passes_test(is_customer)
def product_list(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'food/product_list.html', context)
    

@login_required
@user_passes_test(is_customer)
def add_to_cart(request, product_id):
    order, created = Order.objects.get_or_create(user=request.user, completed=False)
    product = get_object_or_404(Product, id=product_id)
    order_item, created = OrderItem.objects.get_or_create(order=order, product=product)
    order_item.quantity += 1
    order_item.save()

    return redirect('food:product_list')

@login_required
@user_passes_test(is_customer)
def cart_view(request):
    order = Order.objects.filter(user=request.user, completed=False).first()
    numbers = range(1, 101)
    selected_number = None

    if request.method == "POST":
        selected_number = int(request.POST.get("numbers"))
        item_id = request.POST.get('item_id')
        order_item = OrderItem.objects.get(pk=item_id)
        order_item.quantity = selected_number
        order_item.save()

    context = {
        'numbers': numbers,
        'selected_number': selected_number,
        'order': order
    }

    return render(request, 'food/cart_detail.html', context)

def delete_order_item(request, item_id):
    try:
        order_item = OrderItem.objects.get(pk=item_id, order__user=request.user, order__completed=False)
        order_item.delete()
    except OrderItem.DoesNotExist:
        pass

    return redirect('food:cart_view')

@login_required
@user_passes_test(is_customer)
def checkout(request):
    order = Order.objects.get(user=request.user, completed=False)
    total = order.get_total()
    print(total)  
    order.checkout = True
    order.save()

    from channels.layers import get_channel_layer
    from asgiref.sync import async_to_sync
    order_data = {
        'id': order.id,
        'created_at': order.created_at.strftime("%Y-%m-%d %H:%M:%S"),
        'total': str(order.get_total),
        'user_id': order.user.id,
    }

    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        'orders',
        {
            'type': 'order.message',
            'order': order_data
        }
    )
    return redirect('food:preparing')

@login_required
@user_passes_test(is_staff)
def deliver(request):
    orders = Order.objects.filter(completed=False, checkout=True)
    if request.method =='POST':
        order_id = request.POST.get('order_id')
        order_user = request.POST.get('order_user')
        print(order_id) 
        print(order_user)
        order = Order.objects.get(pk=order_id)
        order.completed = True
        order.save()
        order_completed.send(sender=Order, user=order_user, instance=order, completed=order.completed)
        from channels.layers import get_channel_layer
        from asgiref.sync import async_to_sync
        channel_layer = get_channel_layer()
        event_data = {
            'user_id': order_user,
            'redirect_url': '/served',
        }
        async_to_sync(channel_layer.group_send)(
            f'user_{order_user}',
            {
                'type': 'check_redirect',
                'event': event_data,
            }
        )
    return render(request, 'food/deliver.html' , {'orders':orders})

def served(request):
    return render(request, 'food/served.html')

def preparing(request):
    user_id = request.user.id
    return render(request, 'food/preparing.html',{'user_id':user_id})

food/templates/food/cart_detail.html
{% extends "food/home.html" %}
{% block content %}
<h1>Your Shopping Cart</h1>
<script>
    function submitForm(itemId) {
        document.getElementById('dropdown-form-' + itemId).submit();
    }
</script>

{% if order.items.exists %}
    <ul>
        {% for item in order.items.all %}
            <li>
                <form id="dropdown-form-{{ item.id }}" method="post" action="">
                    {% csrf_token %}
                    <input type="hidden" name="item_id" value="{{ item.id }}">
                    <label for="numbers">Choose a number:</label>
                    <select id="numbers" name="numbers" onchange="submitForm({{ item.id }})">
                        {% for i in numbers %}
                            <option value="{{ i }}" {% if i == item.quantity %}selected{% endif %}>{{ i }}</option>
                        {% endfor %}
                    </select>
                    {{ item.quantity }} x {{ item.product.name }} - ${{ item.get_total }}
                </form>
                <form method="post" action="{% url 'food:delete_order_item' item.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    
    
    <p>Total: ${{ order.get_total }}</p>
    <a href="{% url 'food:checkout' %}">Checkout</a>
{% else %}
    <p>Your cart is empty.</p>
{% endif %}
{% endblock %}

food/templates/food/deliver.html
<form method="post" action="{% url 'food:logout' %}">
    {% csrf_token %}
    <button type="submit">Logout</button>
</form>

<h1>Your Order History</h1>
{% if orders %}
    <ul>
        {% for order in orders %}
            <li>
                <form  method="post" action="">
                    {% csrf_token %}
                    Order {{ order.id }} from {{ order.created_at }} - ${{ order.get_total }}
                    <input type="hidden" name="order_id" value="{{ order.id }}">
                    <input type="hidden" name="order_user" value="{{ order.user.id }}">
                    <button type="submit">Deliver</button>
                </form>
            </li>

        {% endfor %}
    </ul>
    <script>
        const orderSocket = new WebSocket('ws://' + window.location.host + '/ws/orders/');

        orderSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            const order = data.order;

            const ordersList = document.querySelector('ul');
            const newOrderItem = document.createElement('li');
            newOrderItem.innerHTML = `
                <form method="post" action="">
                    <input type="hidden" name="order_id" value="${order.id}">
                    <input type="hidden" name="order_user" value="${order.user_id}">
                    Order ${order.id} from ${order.created_at} - $${order.get_total}
                    <button type="submit">Deliver</button>
                </form>
            `;
            ordersList.appendChild(newOrderItem);
        };

        orderSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
    </script>
{% else %}
    <p>You have no past orders.</p>
{% endif %}

food/templates/food/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">FoodApp</a>
          <div class="d-flex">
            <ul class="navbar-nav">
                {% if request.path == '/product_list/' %}
                <li class="nav-item">
                    <a class='nav-link' href="{% url 'food:cart_view' %}">Go To Cart</a>
                </li>
                {% endif %}
                {% if request.path == '/cart/' %}
                <li class="nav-item">
                    <a class='nav-link' href="{% url 'food:product_list' %}">Back</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'food:logout' %}">Logout</a>
                </li>
                
            </ul>
            
            
          </div>
          
        </div>
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

food/templates/food/login.html
<!-- myapp/templates/myapp/login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .login-container {
            max-width: 400px;
            width: 100%;
            padding: 15px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: #ffffff;
        }
        .form-floating {
            margin-bottom: 1rem;
        }
    </style>
</head>
<body>
    
    <div class="login-container">
        <h2 class="text-center">Login</h2>
        <form method="POST" action="{% url 'food:login' %}">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="username" name="username" class="form-control" id="floatingInput" placeholder="Username" required>
                <label for="floatingInput"></label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password" required>
                <label for="floatingPassword"></label>
            </div>
            <button type="submit" class="btn btn-primary w-100">Login</button>

        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.min.js"></script>

</body>
</html>

food/templates/food/order_history.html
{% block content %}
<h1>Your Order History</h1>
{% if orders %}
    <ul>
        {% for order in orders %}
            <li>Order {{ order.id }} from {{ order.created_at }} - ${{ order.get_total }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>You have no past orders.</p>
{% endif %}
{% endblock %}

food/templates/food/preparing.html
<h1>preparing...</h1>
<!-- template.html -->
<script>
    const userId = '{{ user_id }}'; 
    const protocol = window.location.protocol === 'https:' ? 'wss://' : 'ws://';
    const socketURL = protocol + window.location.host + `/ws/preparing/${userId}/`;

    const socket = new WebSocket(socketURL);

    socket.onmessage = function(event) {
        const data = JSON.parse(event.data);
        if (data.redirect_url) {
            window.location.href = data.redirect_url;
        }
    };
    
    // Send a message
    socket.onopen = function(event) {
        socket.send(JSON.stringify({
            'message': 'Hello server!'
        }));
    };
</script>

food/templates/food/product_list.html
{% extends "food/home.html" %}
<!DOCTYPE html>
<html>
<head>
    <title>Product List</title>
</head>
<body>
    {% block content %}
    {% for product in products %}
    <div class="row p-2">
        <div class="col-md-3 offset-md-2">
            <img src="{{ product.image.url}}" class="img-fluid card">
        </div>
        <div class="col-md-4">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">${{ product.price }}</p>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:add_to_cart' product.id %}">Add to Cart</a>
        </div>    
        <br>
    </div>
    {% empty %}
        <p>No products available.</p>
    
        
    {% endfor %}

    
    
    {% endblock %}
</body>
</html>

food/templates/food/served.html
<h1>YOUR ORDER IS READY!</h1>
    

food/templates/food/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>